version: '3.1'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - postgres-net
networks:
  postgres-net:
    driver: bridge
    name: postgres-net
