version: '3'
services: 
  keycloak:
    build: .
    environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://db/keycloak
        KC_DB_USERNAME: postgres
        KC_DB_PASSWORD: postgres
        KC_DB_SCHEMA: public
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: localhost
        KC_HOSTNAME: localhost
        KC_HEALTH_ENABLED: true 
        KC_METRICS_ENABLED: true
    command: --verbose start --optimized
    ports: 
      - 8080:8080
      - 8443:8443
    networks:
        - keycloak-net
networks:
  keycloak-net: 
    driver: bridge
    name: keycloak-net
    external: true
