# Generated by Django 4.2.3 on 2023-07-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.TextField(db_column="filename")),
                ("bucket", models.TextField(db_column="bucket")),
                ("size", models.PositiveBigIntegerField(db_column="size")),
                ("processed", models.BooleanField(db_column="processed")),
                ("uploadtime", models.DateField(db_column="uploadtime")),
                ("tag", models.TextField(db_column="uuidtag")),
                ("filetype", models.TextField(db_column="type")),
            ],
            options={
                "db_table": "upload",
            },
        ),
    ]
